version: '3'
services:
  db:
    image: postgres:14
    ports:
      - 5333:5432
    environment:
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
