# Database Configuration
spring:
  application:
    name: realEstateManager
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_username
    password: your_password
  jpa:
    show-sql: true

# Flyway Migration
  flyway:
    enabled: true
    baseline-on-migrate: true

# GraphQL Configuration
